// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaffleSalesSystemDataAccess;

#nullable disable

namespace WaffleSalesSystemDataAccess.Migrations
{
    [DbContext(typeof(WaffleSalesDbContext))]
    [Migration("20220803203409_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_general_ci")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");

            modelBuilder.Entity("WaffleSalesSystem.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedDatetime")
                        .HasColumnType("datetime");

                    b.Property<sbyte>("IsActive")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Categorydetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "CatId");

                    b.ToTable("categorydetail", (string)null);
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Sale", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("SalesDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SalesName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Salesdetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int?>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("productQuantity");

                    b.Property<int?>("SalesPrice")
                        .HasColumnType("int")
                        .HasColumnName("salesPrice");

                    b.HasKey("Id");

                    b.ToTable("salesdetail", (string)null);
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Stock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("StockPrice")
                        .HasColumnType("int");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Categorydetail", b =>
                {
                    b.HasOne("WaffleSalesSystem.Entity.Category", "Category")
                        .WithMany("Categorydetails")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CatId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WaffleSalesSystem.Entity.Category", b =>
                {
                    b.Navigation("Categorydetails");
                });
#pragma warning restore 612, 618
        }
    }
}
